# syntax=docker/dockerfile:1
version: '3.9'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
    - "6379:6379"
    volumes:
    - $PWD/redis-data:/var/lib/redis
    environment:
    - REDIS_REPLICATION_MODE=master
    networks:
      - metmus_network

networks:
  metmus_network:
    driver: bridge